from typing import Dict, NamedTuple, Optional

from BaseClasses import Item, ItemClassification

ALLIANCE_STARTING_REGIONS = {
    0: "Khenarthi's Roost Access",  # AD
    1: "Stros M'kai Access",        # DC
    2: "Bleakrock Isle Access",     # EP
}

eso_base_id: int = 150000
eso_region_unlock_id: int = eso_base_id
eso_skill_unlock_id: int = eso_base_id

class ESOItem(Item):
    game: str = "Elder Scrolls Online"

class ESOItemData(NamedTuple):
    category:str
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.filler
    max_quantity: int = 1
    weight: int = 1

def get_items_by_category(category: str) -> Dict[str, ESOItemData]:
    item_dict: Dict[str, ESOItemData] = {}
    for name, data in item_table.items():
        if data.category == category:
            item_dict.setdefault(name, data)

    return item_dict

def get_starting_region_item_name(alliance_value: int) -> str:
    return ALLIANCE_STARTING_REGIONS[alliance_value]

item_table: Dict[str, ESOItemData] = {
    "Skyshard":                 ESOItemData("Filler",       eso_base_id-6),
    "Victory":                  ESOItemData("Main Quest",   eso_base_id-5,              ItemClassification.progression,0),
    "Progressive Main Quest":   ESOItemData("Main Quest",   eso_base_id-4,              ItemClassification.progression,11),
    "Stros M'kai Access":       ESOItemData("Zone Access",  eso_region_unlock_id+534,   ItemClassification.progression),
    "Glenumbra Access":         ESOItemData("Zone Access",  eso_region_unlock_id+3,     ItemClassification.progression),
    "Stormhaven Access":        ESOItemData("Zone Access",  eso_region_unlock_id+19,    ItemClassification.progression),
    "Rivenspire Access":        ESOItemData("Zone Access",  eso_region_unlock_id+20,    ItemClassification.progression),
    "Bangkorai Access":         ESOItemData("Zone Access",  eso_region_unlock_id+92,    ItemClassification.progression),
    "Alik'r Desert Access":     ESOItemData("Zone Access",  eso_region_unlock_id+104,   ItemClassification.progression),
    "Betnikh Access":           ESOItemData("Zone Access",  eso_region_unlock_id+535,   ItemClassification.progression),
    "Khenarthi's Roost Access": ESOItemData("Zone Access",  eso_region_unlock_id+537,   ItemClassification.progression),
    "Bleakrock Isle Access":    ESOItemData("Zone Access",  eso_region_unlock_id+280,   ItemClassification.progression),
    "Auridon Access":           ESOItemData("Zone Access",  eso_region_unlock_id+381,   ItemClassification.progression),
    "Grahtwood Access":         ESOItemData("Zone Access",  eso_region_unlock_id+383,   ItemClassification.progression),
    "Greenshade Access":        ESOItemData("Zone Access",  eso_region_unlock_id+108,   ItemClassification.progression),
    "Malabal Tor Access":       ESOItemData("Zone Access",  eso_region_unlock_id+58,    ItemClassification.progression),
    "Reaper's March Access":    ESOItemData("Zone Access",  eso_region_unlock_id+382,   ItemClassification.progression),
    "Bal Foyen Access":         ESOItemData("Zone Access",  eso_region_unlock_id+281,   ItemClassification.progression),
    "Stonefalls Access":        ESOItemData("Zone Access",  eso_region_unlock_id+41,    ItemClassification.progression),
    "Deshaan Access":           ESOItemData("Zone Access",  eso_region_unlock_id+57,    ItemClassification.progression),
    "Shadowfen Access":         ESOItemData("Zone Access",  eso_region_unlock_id+117,   ItemClassification.progression),
    "The Rift Access":          ESOItemData("Zone Access",  eso_region_unlock_id+103,   ItemClassification.progression),
    "Eastmarch Access":         ESOItemData("Zone Access",  eso_region_unlock_id+101,   ItemClassification.progression),
    "Coldharbor Access":        ESOItemData("Zone Access",  eso_region_unlock_id+347,   ItemClassification.progression),
    "Craglorn Access":          ESOItemData("Zone Access",  eso_region_unlock_id+888,   ItemClassification.progression),

    #Skills
    #class Skills
    #Dragonknight
    #Ardent Flame
#    "Dragonknight Standard":    ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Shifting Standard":        ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Standard of Might":        ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Searing Strike":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Venomous Claw":            ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Burning Embers":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fiery Breath":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Noxious Breath":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Engulfing Flames":         ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fiery Grip":               ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Chains of Devastation":    ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Unrelenting Grip":         ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Inferno":                  ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Flames of Oblivion":       ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Cauterize":                ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Combustion":               ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Warmth":                   ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Searing Heat":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "World in Ruin":            ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Draconic Power
#    "Dragon Leap":              ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Take Flight":              ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ferocious Leap":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Spiked Armor":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Hardened Armor":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Volatile Armor":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Dark Talons":              ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Burning Talons":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Choking Talons":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Dragon Blood":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Green Dragon Blood":       ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Coagulating Blood":        ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Protective Scale":         ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Protective Plate":         ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Dragon Fire Scale":        ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Inhale":                   ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Deep Breath":              ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Draw Essence":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Iron Skin":                ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Burning Heat":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Elder Dragon":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Scaled Armor":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Earthen Heart
#    "Magma Armor":              ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Magma Shell":              ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Corrosive Armor":          ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Stonefist":                ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Obsidian Shard":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Stone Giant":              ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Molten Weapons":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Igneous Weapons":          ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Molten Armaments":         ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Obsidian Shield":          ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Igneous Shield":           ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fragmented Shield":        ESOItemData("dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Petrify":                  ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fossilize":                ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Shattering Rocks":         ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ash Cloud":                ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Cinder Storm":             ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Eruption":                 ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Eternal Mountain":         ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Battle Roar":              ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Mountain's Blessing":      ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Helping Hands":            ESOItemData("Dragonknight Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Sorcerer
    #Dark Magic
#    "Negate Magic":             ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Suppression Field":        ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Absorption Field":         ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Crystal Shard":            ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Crystal Weapon":           ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Crystal Fragments":        ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Encase":                   ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Shattering Spines":        ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Vibrant Shroud":           ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Rune Prison":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Rune Cage":                ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Defensive Rune":           ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Dark Exchange":            ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Dark Deal":                ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Dark Conversation":        ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Daedric Mines":            ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Daedric Tomb":             ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Daedric Refuge":           ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Unholy Knowledge":         ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Blood Magic":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Persistence":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Exploitation":             ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
    #Daedric Summoning
#    "Summon Storm Atronach":    ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Greater Storm Atronach":   ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Summon Charged Atronach":  ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Summon Unstable Familiar": ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Summon Unstable Clannfear":ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Summon Volatile Familiar": ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Daedric Curse":            ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Daedric Prey":             ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Haunting Curse":           ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Summon Winged Twilight":   ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Summon Twilight Tormentor":ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Summon Twilight Matriarch":ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Conjured Ward":            ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Hardened Ward":            ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Regenerative Ward":        ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Bound Armor":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Bound Armaments":          ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Bound Aegis":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Rebate":                   ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Power Stone":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Daedric Protection":       ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Expert Summoner":          ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
    #Storm Calling
#    "Overload":                 ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Power Overload":           ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Energy Overload":          ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Mages' Fury":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Mages' Wrath":             ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Endless Fury":             ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Lightning Form":           ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Hurricane":                ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Boundless Storm":          ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Lightning Splash":         ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Liquid Lightning":         ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Lightning Flood":          ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Surge":                    ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Power Surge":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Critical Surge":           ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Bolt Escape":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Streak":                   ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Ball of Lightning":        ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful),
#    "Capacitor":                ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Energized":                ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Amplitude":                ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
#    "Expert Mage":              ESOItemData("Sorcerer Skills",     eso_region_unlock_id, ItemClassification.useful, 2),
    #Nightblade
    #Assassination
#    "Death Stroke":             ESOItemData("Nightblade skills",    eso_skill_unlock_id, ItemClassification.useful),
#    "Incapacitating Strike":    ESOItemData("Nightblade skills",    eso_skill_unlock_id, ItemClassification.useful),
#    "Soul Harvest":             ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Veiled Strike":            ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Surprise Attack":          ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Concealed Weapon":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Teleport Strike":          ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Lotus Fan":                ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ambush":                   ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Assassin's Blade":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Killer's Blade":           ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Impale":                   ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Mark Target":              ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Piercing Mark":            ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Reaper's Mark":            ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Grim Focus":               ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Relentless Focus":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Merciless Resolve":        ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Master Assassin":          ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Executioner":              ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Pressure Points":          ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Hemorrhage":               ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Shadow
#    "Consuming Darkness":       ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Bolstering Darkness":      ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Veil of Blades":           ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Blur":                     ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Mirage":                   ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Phantasmal Escape":        ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Shadow Cloak":             ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Shadowy Disguise":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Dark Cloak":               ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Path of Darkness":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Twisting Path":            ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Refreshing Path":          ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Aspect of Terror":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Mass Hysteria":            ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Manifestation of Terror":  ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Summon Shade":             ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Dark Shade":               ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Shadow Image":             ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Refreshing Shadows":       ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Shadow Barrier":           ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Dark Vigor":               ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Dark Veil":                ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Siphoning
#    "Soul Shread":              ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Soul Siphon":              ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Soul Tether":              ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Strife":                   ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Funnel Health":            ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Swallow Soul":             ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Malevolent Offering":      ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Shrewd Offering":          ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Healthy Offering":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Cripple":                  ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Debilitate":               ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Crippling Grasp":          ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Siphoning Strikes":        ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Leeching Strikes":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Siphoning Attacks":        ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Drain Power":              ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Power Extraction":         ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Sap Essence":              ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Catalyst":                 ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Magicka Flood":            ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Soul Siphoner":            ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Transfer":                 ESOItemData("Nightblade skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Templar
    #Aedric Spear
#    "Radial Sweep":             ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Everlasting Sweep":        ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Crescent Sweep":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Puncturing Strikes":       ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Biting Jabs":              ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Puncturing Sweep":         ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Piercing Javelin":         ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Aurora Javelin":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Binding Javelin":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Focused Charge":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Explosive Charge":         ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Toppling Charge":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Spear Shards":             ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Luminous Shards":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Blazing Spear":            ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Sun Shield":               ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Radiant Ward":             ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Blazing Shield":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Piercing Spear":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Spear Wall":               ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Burning Light":            ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Balanced Warrior":         ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Dawn's Wrath
#    "Nova":                     ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Solar Prison":             ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Solar Disturbance":        ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Sun Fire":                 ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Vampire's Bane":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Reflective Light":         ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Solar Flare":              ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Dark Flare":               ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Solar Barrage":            ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Backlash":                 ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Purifying Light":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Power of the Light":       ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Eclipse":                  ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Living Dark":              ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Unstable Core":            ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Radiant Destruction":      ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Radiant Glory":            ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Radiant Oppression":       ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Enduring Rays":            ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Prism":                    ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Illuminate":               ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Restoring Spirit":         ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Restoring Light
#    "Rite of Passage":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Remembrance":              ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Practiced Incantation":    ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Rushed Ceremony":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Honor the Dead":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Breath of Life":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Healing Ritual":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ritual of Rebirth":        ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Hasty Prayer":             ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Restoring Aura":           ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Radiant Aura":             ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Repentance":               ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Cleansing Ritual":         ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ritual of Retribution":    ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Extended Ritual":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Rune Focus":               ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Channeled Focus":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Restoring Focus":          ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Mending":                  ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Sacred Ground":            ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Light Weaver":             ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Master Ritualist":         ESOItemData("Templar Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Warden
    #Winter's Embrace
#    "Sleet Storm":              ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Northern Storm":           ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Permafrost":               ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Frost Cloak":              ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Expansive Frost Cloak":    ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ice Fortress":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Impaling Shards":          ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Gripping Shards":          ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Winter's Revenge":         ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Arctic Wind":              ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Polar Wind":               ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Arctic Blast":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Crystallized Shield":      ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Crystallized Slab":        ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Shimmering Shield":        ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Frozen Gate":              ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Frozen Device":            ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Frozen Retreat":           ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Glacial Presence":         ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Frozen Armor":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Icy Aura":                 ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Piercing Cold":            ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Green Balance
#    "Secluded Grove":           ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Enchanted Forest":         ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Healing Thicket":          ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fungal Growth":            ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Enchanted Growth":         ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Soothing Spores":          ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Healing Seed":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Budding Seeds":            ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Corrupting Pollen":        ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Living Vines":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Leeching Vines":           ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Living Trellis":           ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Lotus Flower":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Green Lotus":              ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Lotus Blossom":            ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Nature's Grasp":           ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Bursting Vines":           ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Nature's Embrace":         ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Accelerated Growth":       ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Nature's Gift":            ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Emerald Moss":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Maturation":               ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Animal Companions
#    "Feral Guardian":           ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Eternal Guardian":         ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Wild Guardian":            ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Dive":                     ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Cutting Dive":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Screaming Cliff Racer":    ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Scorch":                   ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Subterranean Assault":     ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Deep Fissure":             ESOItemData("warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Swarm":                    ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fetcher Infection":        ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Growing Swarm":            ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Betty Netch":              ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Blue Betty":               ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Bull Netch":               ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Falcon's Swiftness":       ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Deceptive Predator":       ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Bird of Prey":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Bond with Nature":         ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Savage Beast":             ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Flourish":                 ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Advanced Species":         ESOItemData("Warden Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Necromancer
    #Grave Lord
#    "Frozen Colossus":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Pestilence Colossus":      ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Glacial Colossus":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Flame Skull":              ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Venom Skull":              ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ricochet Skull":           ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Sacrificial Bones":        ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Blighted Blastbones":      ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Grave lord's Sacrifice":   ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Boneyard":                 ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Unnerving Boneyard":       ESOItemData('Necromancer Skills', eso_skill_unlock_id, ItemClassification.useful),
#    "Avid Boneyard":            ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Skeletal Mage":            ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Skeletal Archer":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Skeletal Arcanist":        ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Shocking Siphon":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Detonating Siphon":        ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Mystic Siphon":            ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Reusable Parts":           ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Death Knell":              ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Dismember":                ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Rapid Rot":                ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Bone Tyrant
#    "Bone Goliath Transformation":ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Pummeling Goliath":        ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ravenous Goliath":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Death Scythe":             ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ruinous Scythe":           ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Hungry Scythe":            ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Bone Armor":               ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Beckoning Armor":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Summoner's Armor":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Bitter Harvest":           ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Deaden Pain":              ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Necrotic Potency":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Bone Totem":               ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Remote Totem":             ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Agony Totem":              ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Grave Grasp":              ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Ghostly Embrace":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Empowering Grasp":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Death Gleaning":           ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Disdain Harm":             ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Health Avarice":           ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Last Grasp":               ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Living Death
#    "Reanimate":                ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Renewing Animation":       ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Animate Blastbones":       ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Render Flesh":             ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Resistant Flesh":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Blood Sacrifice":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Expunge":                  ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Expunge and Modify":       ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Hexproof":                 ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Life Amid Death":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Renewing Undeath":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Enduring Undeath":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Spirit Mender":            ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Spirit Guardian":          ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Intensive Mender":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Restoring Tether":         ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Braided Tether":           ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Mortal Coil":              ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Curative Curse":           ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Near-Death Experience":    ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Corpse Consumption":       ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Undead Confederate":       ESOItemData("Necromancer Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
	#Arcanist
    #Herald of the tomb
#    "The Unblinking Eye":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "The Tide King's Eye":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "The Languid Eye":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runeblades":				ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Writhing Runeblades":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Escalating Runeblades":	ESOItemData("Arcanist Skills", eso_skill_unlock_id,	ItemClassification.useful),
#    "Fatecarver":				ESOItemData("Arcanist Skills", eso_skill_unlock_id,	ItemClassification.useful),
#    "Exhausting Fatecarver":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Pragmatic Fatecarver":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Abyssal Impact":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Cephaliarch's Flail":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Tentacular Dread":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Tome-Bearer's Inspiration":ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Inspired Scholarship":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Recuperative Treatise":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "The Imperfect Ring":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Rune of Displacement":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fulminating Rune":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fated Fortune":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Harnessed Quintessence":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Psychic Lesion":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Splintered Secrets":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Soldier of Apocrypha
#    "Gibbering Shield":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Sanctum of the Abyssal Sea":ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Gibbering Shelter":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runic Jolt":				ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runic Sunder":				ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runic Embrace":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runespite Ward":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Spiteward of the Lucid Mind":ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Impervious Runeward":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fatewoven Armor":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Cruxweaver Armor":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Unbreakable Fate":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runic Defense":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runeguard of Still Waters":ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runeguard of Freedom":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Rune of Eldritch Horror":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Rune of Uncanny Adoration":ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Rune of Colorless Pool":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Aegis of the Unseen":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Wellspring of the Abyss":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Circumvented Fate":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Implacable Outcome":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
    #Curative Runeforms
#    "Vitalizing Glyphic":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Glyphic of the Tides":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Resonating Glyphic":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Runemend":					ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Evolving Runemend":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Audacious Runemend":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Remedy Cascade":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Casccading Fortune":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Curative Surge":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Chakram Shields":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Chakram of Destiny":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Tidal Chakram":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Arcanist's Domain":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Zenas' Empowering Disc":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Reconstructive Domain":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Apocryphal Gate":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Fleet-Footed Gate":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Passage Between Worlds":	ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful),
#    "Healing Tides":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Hideous Clarity":			ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Erudition":				ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
#    "Intricate Runeforms":		ESOItemData("Arcanist Skills", eso_skill_unlock_id, ItemClassification.useful, 2),
}
