from typing import Dict, NamedTuple, Optional

from BaseClasses import Location
eso_base_id: int = 150000
eso_node_id: int = eso_base_id
eso_quest_id:int = eso_base_id+1000

class ESOLocation(Location):
    game: str = "Elder Scrolls Online"


class ESOLocationData(NamedTuple):
    category: str
    code: Optional[int] = None
    loc_type: str = "wayshrine"

def get_locations_by_category(category: str, world=None) -> Dict[str, ESOLocationData]:
    location_dict: Dict[str, ESOLocationData] = {}

    for name, data in location_table.items():
        if data.category != category:
            continue

        # Apply YAML toggles if world is provided
        if world:
            # Quest toggle
            if data.loc_type == "quest" and not world.options.zone_quests_enabled:
                continue

            # Wayshrine toggle
            if data.loc_type == "wayshrine" and not world.options.wayshrine_checks_enabled:
                continue

        location_dict[name] = data

    return location_dict



location_table: dict[str, ESOLocationData] = {
    "Glenumbra - Wyrd Tree Wayshrine":               ESOLocationData("Glenumbra",       eso_node_id ,"wayshrine"),
    "Glenumbra - Aldcroft Wayshrine":                ESOLocationData("Glenumbra",       eso_node_id+1, "wayshrine"),
    "Glenumbra - Deleyn's Mill Wayshrine":           ESOLocationData("Glenumbra",       eso_node_id+2, "wayshrine"),
    "Glenumbra - Eagle's Brook Wayshrine":           ESOLocationData("Glenumbra",       eso_node_id+3, "wayshrine"),
    "Glenumbra - North Hag Fen Wayshrine":           ESOLocationData("Glenumbra",       eso_node_id+4, "wayshrine"),
    "Glenumbra - Lion Guard Redoubt Wayshrine":      ESOLocationData("Glenumbra",       eso_node_id+5, "wayshrine"),
    "Glenumbra - Crosswych Wayshrine":               ESOLocationData("Glenumbra",       eso_node_id+6, "wayshrine"),
    "Glenumbra - Farwatch Wayshrine":                ESOLocationData("Glenumbra",       eso_node_id+7, "wayshrine"),
    "Rivenspire - Oldgate Wayshrine":                 ESOLocationData("Rivenspire",       eso_node_id+8, "wayshrine"),
    "Rivenspire - Crestshade Wayshrine":              ESOLocationData("Rivenspire",       eso_node_id+9, "wayshrine"),
    "Rivenspire - Camp Tamrith Wayshrine":            ESOLocationData("Rivenspire",       eso_node_id+10, "wayshrine"),
    "Rivenspire - Boralis Wayshrine":                 ESOLocationData("Rivenspire",       eso_node_id+11, "wayshrine"),
    "Rivenspire - Staging Grounds Wayshrine":         ESOLocationData("Rivenspire",       eso_node_id+12, "wayshrine"),
    "Stormhaven - Koeglin Village Wayshrine":         ESOLocationData("Stormhaven",       eso_node_id+13, "wayshrine"),
    "Stormhaven - Alcaire Castle Wayshrine":          ESOLocationData("Stormhaven",       eso_node_id+14, "wayshrine"),
    "Stormhaven - Firebrand Wayshrine":               ESOLocationData("Stormhaven",       eso_node_id+15, "wayshrine"),
    "Stormhaven - Bonesnap Ruins Wayshrine":          ESOLocationData("Stormhaven",       eso_node_id+16, "wayshrine"),
    "Stormhaven - Soulshriven Wayshrine":             ESOLocationData("Stormhaven",       eso_node_id+17, "wayshrine"),
    "Stormhaven - Pariah Abbey Wayshrine":            ESOLocationData("Stormhaven",       eso_node_id+18, "wayshrine"),
    "Glenumbra - Baelborne Rock Wayshrine":          ESOLocationData("Glenumbra",       eso_node_id+19, "wayshrine"),
    "Grahtwood - Elden Root Temple Wayshrine":        ESOLocationData("Grahtwood",        eso_node_id+20, "wayshrine"),
    "Stormhaven - Wind Keep Wayshrine":               ESOLocationData("Stormhaven",       eso_node_id+21, "wayshrine"),
    "Stormhaven - Dro'dara Plantation Wayshrine":     ESOLocationData("Stormhaven",       eso_node_id+22, "wayshrine"),
    "Deshaan - West Narsis Wayshrine":                ESOLocationData("Deshaan",          eso_node_id+23, "wayshrine"),
    "Deshaan - Muth Gnaar Hills Wayshrine":           ESOLocationData("Deshaan",          eso_node_id+24, "wayshrine"),
    "Deshaan - Quarantine Serk Wayshrine":            ESOLocationData("Deshaan",          eso_node_id+25, "wayshrine"),
    "Deshaan - Ghost Snake Vale Washrine":            ESOLocationData("Deshaan",          eso_node_id+26, "wayshrine"),
    "Deshaan - Mournhold Wayshrine":                  ESOLocationData("Deshaan",          eso_node_id+27, "wayshrine"),
    "Deshaan - Tal'Deic Grounds Wayshrine":           ESOLocationData("Deshaan",          eso_node_id+28, "wayshrine"),
    "Deshaan - Obsidian Gorge Wayshrine":             ESOLocationData("Deshaan",          eso_node_id+29, "wayshrine"),
    "Stormhaven - Weeping Giant Wayshrine":           ESOLocationData("Stormhaven",       eso_node_id+30, "wayshrine"),
    "Deshaan - Mzithumz Wayshrine":                   ESOLocationData("Deshaan",          eso_node_id+31, "wayshrine"),
    "Bangkorai - Evermore Wayshrine":                 ESOLocationData("Bangkorai",        eso_node_id+32, "wayshrine"),
    "Bangkorai - Troll's Toothpick Wayshrine":        ESOLocationData("Bangkorai",        eso_node_id+33, "wayshrine"),
    "Bangkorai - Viridian Woods Wayshrine":           ESOLocationData("Bangkorai",        eso_node_id+34, "wayshrine"),
    "Bangkorai - Bangkorai Pass Wayshrine":           ESOLocationData("Bangkorai",        eso_node_id+35, "wayshrine"),
    "Bangkorai - Nalata Ruins Wayshrine":             ESOLocationData("Bangkorai",        eso_node_id+36, "wayshrine"),
    "Bangkorai - Hallin's Stand Wayshrine":           ESOLocationData("Bangkorai",        eso_node_id+37, "wayshrine"),
    "Bangkorai - Old Tower Wayshrine":                ESOLocationData("Bangkorai",        eso_node_id+38, "wayshrine"),
    "Bangkorai - Onsi's Breath Wayshrine":            ESOLocationData("Bangkorai",        eso_node_id+39, "wayshrine"),
    "Stonefalls - Fort Arand Wayshrine":              ESOLocationData("Stonefalls",       eso_node_id+40, "wayshrine"),
    "Alik'r - Morwha's Bounty Wayshrine":             ESOLocationData("Alik'r Desert",    eso_node_id+41, "wayshrine"),
    "Alik'r - Sentinel Wayshrine":                    ESOLocationData("Alik'r Desert",    eso_node_id+42, "wayshrine"),
    "Alik'r - Bergama Wayshrine":                     ESOLocationData("Alik'r Desert",    eso_node_id+43, "wayshrine"),
    "Alik'r - Leki's Blade Wayshrine":                ESOLocationData("Alik'r Desert",    eso_node_id+44, "wayshrine"),
    "Alik'r - Satakalaam Wayshrine":                  ESOLocationData("Alik'r Desert",    eso_node_id+45, "wayshrine"),
    "Shadowfen - Stillrise Wayshrine":                ESOLocationData("Shadowfen",        eso_node_id+46, "wayshrine"),
    "Shadowfen - Stormhold Wayshrine":                ESOLocationData("Shadowfen",        eso_node_id+47, "wayshrine"),
    "Shadowfen - Hatching Pools Wayshrine":           ESOLocationData("Shadowfen",        eso_node_id+48, "wayshrine"),
    "Shadowfen - Alten Corimont Wayshrine":           ESOLocationData("Shadowfen",        eso_node_id+49, "wayshrine"),
    "Shadowfen - Percolating Mire Wayshrine":         ESOLocationData("Shadowfen",        eso_node_id+50, "wayshrine"),
    "Shadowfen - Hissmir Wayshrine":                  ESOLocationData("Shadowfen",        eso_node_id+51, "wayshrine"),
    "Shadowfen - Loriasel Wayshrine":                 ESOLocationData("Shadowfen",        eso_node_id+52, "wayshrine"),
#   "Empty node slot":                                ESOLocationData("N/A",              eso_node_id+53, "wayshrine"),
    "Rivenspire - Shornhelm Wayshrine":               ESOLocationData("Rivenspire",       eso_node_id+54, "wayshrine"),
    "Stormhaven - Wayrest Wayshrine":                 ESOLocationData("Stormhaven",       eso_node_id+55, "wayshrine"),
    "Alik'r - Divad's Chagrin Mine Wayshrine":        ESOLocationData("Alik'r Desert",    eso_node_id+56, "wayshrine"),
    "Alik'r - Kulati Mines Wayshrine":                ESOLocationData("Alik'r Desert",    eso_node_id+57, "wayshrine"),
    "Alik'r - Aswala Stables Wayshrine":              ESOLocationData("Alik'r Desert",    eso_node_id+58, "wayshrine"),
    "Alik'r - Shrikes' Aerie Wayshrine":              ESOLocationData("Alik'r Desert",    eso_node_id+59, "wayshrine"),
    "Alik'r - HoonDing's Watch Wayshrine":            ESOLocationData("Alik'r Desert",    eso_node_id+60, "wayshrine"),
    "Glenumbra - Daggerfall Wayshrine":              ESOLocationData("Menu",             eso_node_id+61, "wayshrine"),
    "Bangkorai - Sunken Road Wayshrine":              ESOLocationData("Bangkorai",        eso_node_id+62, "wayshrine"),
    "Glenumbra - Burial Tombs Wayshrine":            ESOLocationData("Glenumbra",       eso_node_id+63, "wayshrine"),
    "Stonefalls - Davon's Watch Wayshrine":           ESOLocationData("Menu",             eso_node_id+64, "wayshrine"),
    "Stonefalls - Othrenis Wayshrine":                ESOLocationData("Stonefalls",       eso_node_id+65, "wayshrine"),
    "Stonefalls - Ebonheart Wayshrine":               ESOLocationData("Stonefalls",       eso_node_id+66, "wayshrine"),
    "Stonefalls - Vevec's Antlers Wayshrine":         ESOLocationData("Stonefalls",       eso_node_id+67, "wayshrine"),
    "Stonefalls - Sulfur Pools Wayshrine":            ESOLocationData("Stonefalls",       eso_node_id+68, "wayshrine"),
#   "Empty node slot":                                ESOLocationData("N/A",              eso_node_id+69, "wayshrine"),
    "Stonefalls - Brothers of Strife Wayshrine":      ESOLocationData("Stonefalls",       eso_node_id+70, "wayshrine"),
    "Stonefalls - Hrogar's Hold Wayshrine":           ESOLocationData("Stonefalls",       eso_node_id+71, "wayshrine"),
    "Stonefalls - Fort Virak Wayshrine":              ESOLocationData("Stonefalls",       eso_node_id+72, "wayshrine"),
    "Stonefalls - Iliath Temple Wayshrine":           ESOLocationData("Stonefalls",       eso_node_id+73, "wayshrine"),
    "Stonefalls - Sathram Plantation Wayshrine":      ESOLocationData("Stonefalls",       eso_node_id+74, "wayshrine"),
    "Stonefalls - Kragenmoor Wayshrine":              ESOLocationData("Stonefalls",       eso_node_id+75, "wayshrine"),
    "Stonefalls - Ashen Road Wayshrine":              ESOLocationData("Stonefalls",       eso_node_id+76, "wayshrine"),
    "Shadowfen - Venomous Fens Wayshrine":            ESOLocationData("Shadowfen",        eso_node_id+77, "wayshrine"),
    "Deshaan - Selfora Wayshrine":                    ESOLocationData("Deshaan",          eso_node_id+78, "wayshrine"),
    "Deshaan - Silent Mire Wayshrine":                ESOLocationData("Deshaan",          eso_node_id+79, "wayshrine"),
    "Deshaan - Eidolon's Hollow Wayshrine":           ESOLocationData("Deshaan",          eso_node_id+80, "wayshrine"),
    "Rivenspire - Northpoint Wayshrine":              ESOLocationData("Rivenspire",       eso_node_id+81, "wayshrine"),
    "Rivenspire - Fell's Run Wayshrine":              ESOLocationData("Rivenspire",       eso_node_id+82, "wayshrine"),
    "Rivenspire - Hoarfrost Downs Wayshrine":         ESOLocationData("Rivenspire",       eso_node_id+83, "wayshrine"),
    "Shadowfen - Forsaken Hamlet Wayshrine":          ESOLocationData("Shadowfen",        eso_node_id+84, "wayshrine"),
    "Rivenspire - Sanguine Barrows Wayshrine":        ESOLocationData("Rivenspire",       eso_node_id+85, "wayshrine"),
    "Eastmarch - Windhelm Wayshrine":                 ESOLocationData("Eastmarch",        eso_node_id+86, "wayshrine"),
    "Eastmarch - Fort Morvunskar Wayshrine":          ESOLocationData("Eastmarch",        eso_node_id+87, "wayshrine"),
    "Eastmarch - Kynesgrove Wayshrine":               ESOLocationData("Eastmarch",        eso_node_id+88, "wayshrine"),
    "Eastmarch - Voljar Meadery Wayshrine":           ESOLocationData("Eastmarch",        eso_node_id+89, "wayshrine"),
    "Eastmarch - Cradlecrush Wayshrine":              ESOLocationData("Eastmarch",        eso_node_id+90, "wayshrine"),
    "Eastmarch - Fort Amol Wayshrine":                ESOLocationData("Eastmarch",        eso_node_id+91, "wayshrine"),
    "Eastmarch - Wittestadr Wayshrine":               ESOLocationData("Eastmarch",        eso_node_id+92, "wayshrine"),
    "Eastmarch - Mistwatch Wayshrine":                ESOLocationData("Eastmarch",        eso_node_id+93, "wayshrine"),
    "Eastmarch - Jorunn's Stand Wayshrine":           ESOLocationData("Eastmarch",        eso_node_id+94, "wayshrine"),
    "Eastmarch - Logging Camp Wayshrine":             ESOLocationData("Eastmarch",        eso_node_id+95, "wayshrine"),
    "Eastmarch - Skuldafn Wayshrine":                 ESOLocationData("Eastmarch",        eso_node_id+96, "wayshrine"),
    "Stonefalls - Fungal Grotto Dungeon Found":       ESOLocationData("Stonefalls",       eso_node_id+97, "wayshrine"),
    "Malabal Tor - Ilayas Ruins Wayshrine":           ESOLocationData("Malabal Tor",      eso_node_id+98, "wayshrine"),
    "Malabal Tor - Vulkwasten Wayshrine":             ESOLocationData("Malabal Tor",      eso_node_id+99, "wayshrine"),
    "Malabal Tor - Dra'Bul Wayshrine":                ESOLocationData("Malabal Tor",      eso_node_id+100, "wayshrine"),
    "Malabal Tor - Velyn Harbor Wayshrine":           ESOLocationData("Malabal Tor",      eso_node_id+101, "wayshrine"),
    "Malabal Tor - Bloodtoil Wayshrine":              ESOLocationData("Malabal Tor",      eso_node_id+102, "wayshrine"),
    "Malabal Tor - Abamath Wayshrine":                ESOLocationData("Malabal Tor",      eso_node_id+103, "wayshrine"),
    "Malabal Tor - Wilding Run Wayshrine":            ESOLocationData("Malabal Tor",      eso_node_id+104, "wayshrine"),
    "Malabal Tor - Baandari Market Wayshrine":        ESOLocationData("Malabal Tor",      eso_node_id+105, "wayshrine"),
    "Malabal Tor - Valeguard Wayshrine":              ESOLocationData("Malabal Tor",      eso_node_id+106, "wayshrine"),
    "Stonefalls - Senie Wayshrine":                   ESOLocationData("Stonefalls",       eso_node_id+107, "wayshrine"),
    "The Rift - Riften Wayshrine":                    ESOLocationData("The Rift",         eso_node_id+108, "wayshrine"),
    "The Rift - Skald's Retreat Wayshrine":           ESOLocationData("The Rift",         eso_node_id+109, "wayshrine"),
    "The Rift - Trolhetta Wayshrine":                 ESOLocationData("The Rift",         eso_node_id+110, "wayshrine"),
    "The Rift - Trolhetta Summit Wayshrine":          ESOLocationData("The Rift",         eso_node_id+111, "wayshrine"),
    "The Rift - Honrich Tower Wayshrine":             ESOLocationData("The Rift",         eso_node_id+112, "wayshrine"),
    "The Rift - Fallowstone Hall Waystone":           ESOLocationData("The Rift",         eso_node_id+113, "wayshrine"),
    "The Rift - Northwind Mine Wayshrine":            ESOLocationData("The Rift",         eso_node_id+114, "wayshrine"),
    "The Rift - Geirmund's Hall Wayshrine":           ESOLocationData("The Rift",         eso_node_id+115, "wayshrine"),
    "The Rift - Taarengrav Wayshrine":                ESOLocationData("The Rift",         eso_node_id+116, "wayshrine"),
    "The Rift - Nimalten Wayshrine":                  ESOLocationData("The Rift",         eso_node_id+117, "wayshrine"),
    "The Rift - Ragged Hills Wayshrine":              ESOLocationData("The Rift",         eso_node_id+118, "wayshrine"),
    "The Rift - Fullhelm Fort Wayshrine":             ESOLocationData("The Rift",         eso_node_id+119, "wayshrine"),
    "Auridon - Skywatch Wayshrine":                   ESOLocationData("Auridon",          eso_node_id+120, "wayshrine"),
    "Auridon - Quendeluun Wayshrine":                 ESOLocationData("Auridon",          eso_node_id+121, "wayshrine"),
    "Auridon - Collage Wayshrine":                    ESOLocationData("Auridon",          eso_node_id+122, "wayshrine"),
    "Auridon - Greenwater Wayshrine":                 ESOLocationData("Auridon",          eso_node_id+123, "wayshrine"),
    "Bal Foyen - Fort Zeren Wayshrine":               ESOLocationData("Bal Foyen",        eso_node_id+124, "wayshrine"),
    "Bal Foyen - Foyen Docks Wayshrine":              ESOLocationData("Bal Foyen",        eso_node_id+125, "wayshrine"),
    "Auridon - Windy Glade Wayshrine":                ESOLocationData("Auridon",          eso_node_id+126, "wayshrine"),
#   "Coldharbour - Library of Dusk Wayshrine":        ESOLocationData("Coldharbour",      eso_node_id+127, "wayshrine"),
#   "Coldharbour - Great Shackle Wayshrine":          ESOLocationData("Coldharbour",      eso_node_id+128, "wayshrine"),
#   "Coldharbour - The Chasm Wayshrine":              ESOLocationData("Coldharbour",      eso_node_id+129, "wayshrine"),
#   "Coldharbour - Hollow City Wayshrine":            ESOLocationData("Coldharbour",      eso_node_id+130, "wayshrine"),
#   "Coldharbour - Endless Stair Wayshrine":          ESOLocationData("Coldharbour",      eso_node_id+131, "wayshrine"),
#   "Coldharbour - Everfull Flagon Wayshrine":        ESOLocationData("Coldharbour",      eso_node_id+132, "wayshrine"),
#   "Coldharbour - Moonless Walk Wayshrine":          ESOLocationData("Coldharbour",      eso_node_id+133, "wayshrine"),
#   "Coldharbour - Haj Uxith Wayshrine":              ESOLocationData("Coldharbour",      eso_node_id+134, "wayshrine"),
#   "Coldharbour - Manor of Revelry Wayshrine":       ESOLocationData("Coldharbour",      eso_node_id+135, "wayshrine"),
    "Alik'r - Sep's Spine Wayshrine":                 ESOLocationData("Alik'r Desert",    eso_node_id+136, "wayshrine"),
    "Stros M'kai - Port Hunding Wayshrine":           ESOLocationData("Stros M'kai",      eso_node_id+137, "wayshrine"),
#   "Coldharbour - Reaver Citadel Wayshrine":         ESOLocationData("Coldharbour",      eso_node_id+138, "wayshrine"),
#   "Coldharbour - The Orchard Wayshrine":            ESOLocationData("Coldharbour",      eso_node_id+139, "wayshrine"),
    "Khenarthi's Roost - Khenarthi's Roost Wayshrine":ESOLocationData("Khenarthi's Roost",eso_node_id+140, "wayshrine"),
    "Khenarthi's Roost - Mistral Wayshrine":          ESOLocationData("Khenarthi's Roost",eso_node_id+141, "wayshrine"),
    "Greenshade - Marbruk Wayshrine":                 ESOLocationData("Greenshade",       eso_node_id+142, "wayshrine"),
    "Reaper's March - Vinedusk Wayshrine":            ESOLocationData("Reaper's March",   eso_node_id+143, "wayshrine"),
#   "Coldharbour - Shrouded Plains Wayshrine":        ESOLocationData("Coldharbour",      eso_node_id+144, "wayshrine"),
#   "Coldharbour - Court of Contempt Wayshrine":      ESOLocationData("Coldharbour",      eso_node_id+145, "wayshrine"),
    "Greenshade - Greenheart Wayshrine":              ESOLocationData("Greenshade",       eso_node_id+146, "wayshrine"),
    "Greenshade - Labyrinth Wayshrine":               ESOLocationData("Greenshade",       eso_node_id+147, "wayshrine"),
    "Greenshade - Falinesti Wayshrine":               ESOLocationData("Greenshade",       eso_node_id+148, "wayshrine"),
    "Greenshade - Seaside Sanctuary":                 ESOLocationData("Greenshade",       eso_node_id+149, "wayshrine"),
    "Greenshade - Verrant Morass Wayshrine":          ESOLocationData("Greenshade",       eso_node_id+150, "wayshrine"),
    "Greenshade - Woodhearth Wayshrine":              ESOLocationData("Greenshade",       eso_node_id+151, "wayshrine"),
    "Greenshade - Moonhendge Wayshrine":              ESOLocationData("Greenshade",       eso_node_id+152, "wayshrine"),
    "Greenshade - Serpent's Grotto Wayshrine":        ESOLocationData("Greenshade",       eso_node_id+153, "wayshrine"),
    "Alik'r - Goat's Head Oasis Wayshrine":           ESOLocationData("Alik'r Desert",    eso_node_id+154, "wayshrine"),
    "Reaper's March - Fort Grimwatch Wayshrine":      ESOLocationData("Reaper's March",   eso_node_id+155, "wayshrine"),
    "Reaper's March - Fort Sphinxmoth Wayshrine":     ESOLocationData("Reaper's March",   eso_node_id+156, "wayshrine"),
    "Reaper's March - Arenthia Wayshrine":            ESOLocationData("Reaper's March",   eso_node_id+157, "wayshrine"),
    "Reaper's March - Dune Wayshrine":                ESOLocationData("Reaper's March",   eso_node_id+158, "wayshrine"),
    "Reaper's March - Willowgrove Wayshrine":         ESOLocationData("Reaper's March",   eso_node_id+159, "wayshrine"),
    "Reaper's March - Moonmont Wayshrine":            ESOLocationData("Reaper's March",   eso_node_id+160, "wayshrine"),
    "Reaper's March - Rawl'kha Wayshrine":            ESOLocationData("Reaper's March",   eso_node_id+161, "wayshrine"),
    "Reaper's March - S'ren-ja Wayshrine":            ESOLocationData("Reaper's March",   eso_node_id+162, "wayshrine"),
    "Grahtwood - Gil-Var-Delle Wayshrine":            ESOLocationData("Grahtwood",        eso_node_id+163, "wayshrine"),
    "Grahtwood - Haven Wayshrine":                    ESOLocationData("Grahtwood",        eso_node_id+164, "wayshrine"),
    "Grahtwood - Redfur Trading Post Wayshrine":      ESOLocationData("Grahtwood",        eso_node_id+165, "wayshrine"),
    "Grahtwood - Southpoint Wayshrine":               ESOLocationData("Grahtwood",        eso_node_id+166, "wayshrine"),
    "Grahtwood - Cormount Wayshrine":                 ESOLocationData("Grahtwood",        eso_node_id+167, "wayshrine"),
    "Grahtwood - Ossuary Wayshrine":                  ESOLocationData("Grahtwood",        eso_node_id+168, "wayshrine"),
#   "Cyrodiil - North High Rock Gate Wayshrine":      ESOLocationData("Cyrodiil",         eso_node_id+169, "wayshrine"),
    "Shadowfen - Bogmother Wayshrine":                ESOLocationData("Shadowfen",        eso_node_id+170, "wayshrine"),
    "Bleakrock Isle - Bleakrock Wayshrine":           ESOLocationData("Bleakrock Isle",   eso_node_id+171, "wayshrine"),
    "Bal Foyen - Dhalmora Wayshrine":                 ESOLocationData("Bal Foyen",        eso_node_id+172, "wayshrine"),
    "Auridon - Tanelwil Wayshrine":                   ESOLocationData("Auridon",          eso_node_id+173, "wayshrine"),
    "Auridon - Firsthold Wayshrine":                  ESOLocationData("Auridon",          eso_node_id+174, "wayshrine"),
    "Auridon - Mathiisen Wayshrine":                  ESOLocationData("Auridon",          eso_node_id+175, "wayshrine"),
    "Auridon - Vulkhel Guard Wayshrine":              ESOLocationData("Menu",             eso_node_id+176, "wayshrine"),
    "Auridon - Phaer Wayshrine":                      ESOLocationData("Auridon",          eso_node_id+177, "wayshrine"),
    "Stros M'kai - Sandy Grotto Wayshrine":           ESOLocationData("Stros M'kai",      eso_node_id+178, "wayshrine"),
    "Stros M'kai - Saintsport Wayshrine":             ESOLocationData("Stros M'kai",      eso_node_id+179, "wayshrine"),
    "Betnikh - Stonetooth Wayshrine":                 ESOLocationData("Betnikh",          eso_node_id+180, "wayshrine"),
    "Betnikh - Grimfield Wayshrine":                  ESOLocationData("Betnikh",          eso_node_id+181, "wayshrine"),
    "Betnikh - Carved Hills Wayshrine":               ESOLocationData("Betnikh",          eso_node_id+182, "wayshrine"),
#   "Coldharbour - Vaults of Madness Dungeon Found":  ESOLocationData("Coldharbour",      eso_node_id+183, "wayshrine"),
#   "Reaper's March - Selene's Web Dungeon Found":    ESOLocationData("Reaper's March",   eso_node_id+184, "wayshrine"),
#   "Bangkorai - Blackheart Dungeon Found":           ESOLocationData("Bangkorai",        eso_node_id+185, "wayshrine"),
#   "The Rift - Blessed Crucible Dungeon Found":      ESOLocationData("The Rift",         eso_node_id+186, "wayshrine"),
#   "Malabal Tor - Tempest Island Dungeon Found":     ESOLocationData("Malabal Tor",      eso_node_id+187, "wayshrine"),
#   "Stormhaven - Wayrest Sewers Dungeon Found":      ESOLocationData("Stormhaven",       eso_node_id+188, "wayshrine"),
#   "Rivenspire - Crypt of Hearts Dungeon Found":     ESOLocationData("Rivenspire",       eso_node_id+189, "wayshrine"),
#   "Grahtwood - Elden Hollow Dungeon Found":         ESOLocationData("Grahtwood",        eso_node_id+190, "wayshrine"),
#   "Shadowfen - Arx Corinium Dungeon Found":         ESOLocationData("Shadowfen",        eso_node_id+191, "wayshrine"),
#   "Glenumbra - Spindleclutch Dungeon Found":        ESOLocationData("Glenumbra",        eso_node_id+192, "wayshrine"),
#   "Auridon - The Banished Cells Dungeon Found":     ESOLocationData("Auridon",          eso_node_id+193, "wayshrine"),
#   "Eastmarch - Direfrost Keep Dungeon Found":       ESOLocationData("Eastmarch",        eso_node_id+194, "wayshrine"),
#   "Alik'r - Volenfell Dungeon Found":               ESOLocationData("Alik'r Desert",    eso_node_id+195, "wayshrine"),
#   "Greenshade - City of Ash Dungeon Found":         ESOLocationData("Greenshade",       eso_node_id+196, "wayshrine"),
#   "Deshaan - Darkshade Caverns Dungeon Found":      ESOLocationData("Deshaan",          eso_node_id+197, "wayshrine"),
#   "Cyrodiil - Southern High Rock Gate Wayshrine":   ESOLocationData("Cyrodiil",         eso_node_id+198, "wayshrine"),
#   "Cyrodiil - Eastern Elsweyr Gate Wayshrine":      ESOLocationData("Cyrodiil",         eso_node_id+199, "wayshrine"),
#   "Cyrodiil - Western Elsweyr Gate Wayshrine":      ESOLocationData("Cyrodiil",         eso_node_id+200, "wayshrine"),
#   "Cyrodiil - Northern Morrowind Gate Wayshrine":   ESOLocationData("Cyrodiil",         eso_node_id+201, "wayshrine"),
#   "Cyrodiil - Southern Morrowind Gate Wayshrine":   ESOLocationData("Cyrodiil",         eso_node_id+202, "wayshrine"),
    "Bangkorai - Eastern Evermore Wayshrine":         ESOLocationData("Bangkorai",        eso_node_id+203, "wayshrine"),
    "Deshaan - Shad Astula Wayshrine":                ESOLocationData("Deshaan",          eso_node_id+204, "wayshrine"),
    "Bangkorai - Halcyon Lake Wayshrine":             ESOLocationData("Bangkorai",        eso_node_id+205, "wayshrine"),
    "Grahtwood - Gray Mire Wayshrine":                ESOLocationData("Grahtwood",        eso_node_id+206, "wayshrine"),
    "Rivenspire - Shrouded Pass Wayshrine":           ESOLocationData("Rivenspire",       eso_node_id+207, "wayshrine"),
#   "Empty Node Slot":                                ESOLocationData("N/A",              eso_node_id+208, "wayshrine"),
#   "The Harborage":                                  ESOLocationData("N/A",              eso_node_id+209, "wayshrine"),
#   "The Harborage":                                  ESOLocationData("N/A",              eso_node_id+210, "wayshrine"),
#   "The Harborage":                                  ESOLocationData("N/A",              eso_node_id+211, "wayshrine"),
    "Grahtwood - Falinesti Winter Wayshrine":         ESOLocationData("Grahtwood",        eso_node_id+212, "wayshrine"),
    "Grahtwood - Elden Root Wayshrine":               ESOLocationData("Grahtwood",        eso_node_id+213, "wayshrine"),
#   "Eyevea - Eyevea Wayshrine":                      ESOLocationData("Eyevea",           eso_node_id+214, "wayshrine"),
    "Glenumbra - Hag Fen Wayshrine":                 ESOLocationData("Glenumbra",       eso_node_id+215, "wayshrine"),
    "Craglorn - Seeker's Archive Wayshrine":          ESOLocationData("Craglorn",         eso_node_id+216, "wayshrine"),
    "Craglorn - Shada's Tear Wayshrine":              ESOLocationData("Craglorn",         eso_node_id+217, "wayshrine"),
    "Craglorn - Sandy Path Wayshrine":                ESOLocationData("Craglorn",         eso_node_id+218, "wayshrine"),
    "Craglorn - Belkarth Wayshrine":                  ESOLocationData("Craglorn",         eso_node_id+219, "wayshrine"),
#   "Craglorn - The Earth Forge":                     ESOLocationData("Craglorn",         eso_node_id+220, "wayshrine"),
#   "Empty":                                          ESOLocationData("N/A",              eso_node_id+221, "wayshrine"),
#   "Empty":                                          ESOLocationData("N/A",              eso_node_id+222, "wayshrine"),
#   "Empty":                                          ESOLocationData("N/A",              eso_node_id+223, "wayshrine"),
    "Craglorn - Spellscar Wayshrine":                 ESOLocationData("Craglorn",         eso_node_id+224, "wayshrine"),
    "Craglorn - Mountain Overlook Wayshrine":         ESOLocationData("Craglorn",         eso_node_id+225, "wayshrine"),
    "Craglorn - Inzzur's Hold Wayshrine":             ESOLocationData("Craglorn",         eso_node_id+226, "wayshrine"),
#   "Empty":                                          ESOLocationData("N/A",              eso_node_id+227, "wayshrine"),
    "Craglorn - Elinhir Wayshrine":                   ESOLocationData("Craglorn",         eso_node_id+228, "wayshrine"),
#   "Craglorn - Hel Ra Citadel":                      ESOLocationData("Craglorn",         eso_node_id+229, "wayshrine"),
#   "Craglorn - Aetherian Archive":                   ESOLocationData("Craglorn",         eso_node_id+230, "wayshrine"),
#   "Craglorn - Sanctum Ophidia":                     ESOLocationData("Craglorn",         eso_node_id+231, "wayshrine"),
    "Craglorn - Dragonstar Wayshrine":                ESOLocationData("Craglorn",         eso_node_id+232, "wayshrine"),
    "Craglorn - Skyreach Wayshrine":                  ESOLocationData("Craglorn",         eso_node_id+233, "wayshrine"),
    "Craglorn - Valley of Scars Wayshrine":           ESOLocationData("Craglorn",         eso_node_id+234, "wayshrine"),

    #Quests
    "Stros M'kai - Like Moths to a Candle Zone Quest":ESOLocationData("Stros M'kai",     eso_quest_id + 4344, "zone quest"),
    "Stros M'kai - Buried Secrets Zone Quest":        ESOLocationData("Stros M'kai",     eso_quest_id + 4431, "zone quest"),
    "Stros M'kai - Innocent Scoundral Zone Quest":    ESOLocationData("Stros M'kai",     eso_quest_id + 4454, "zone quest"),
    "Stros M'kai - The Broken Spearhead / The Spearheads Captain Zone Quest":  ESOLocationData("Stros M'kai",     eso_quest_id + 4466, "zone quest"),
    "Stros M'kai - Tip of the Spearhead Zone Quest":  ESOLocationData("Stros M'kai",     eso_quest_id + 4476, "zone quest"),

    "Betnikh - The Bloodthorn Plot Zone Quest":       ESOLocationData("Betnikh",         eso_quest_id + 4523, "zone quest"),
    "Betnikh - Into The Hills Zone Quest":            ESOLocationData("Betnikh",         eso_quest_id + 4478, "zone quest"),
    "Betnikh - Tormented Souls Zone Quest":           ESOLocationData("Betnikh",         eso_quest_id + 4525, "zone quest"),
    "Betnikh - Unearthing the Past Zone Quest":       ESOLocationData("Betnikh",         eso_quest_id + 4468, "zone quest"),
    "Betnikh - Carzog's Demise Zone Quest":           ESOLocationData("Betnikh",         eso_quest_id + 4449, "zone quest"),
    "Betnikh - On to Glenumbria Zone Quest":          ESOLocationData("Betnikh",         eso_quest_id + 4566, "zone quest"),

    "Glenumbra - Blood and the Crecent Moon Zone Quest":ESOLocationData("Glenumbra",     eso_quest_id + 3000, "zone quest"),
    "Glenumbra - Bloodthorn Assassins Zone Quest":      ESOLocationData("Glenumbra",     eso_quest_id + 3006, "zone quest"),
    "Glenumbra - Turning of the Trees Zone Quest":      ESOLocationData("Glenumbra",     eso_quest_id + 3009, "zone quest"),
    "Glenumbra - Ash and Reprive Zone Quest":           ESOLocationData("Glenumbra",     eso_quest_id + 2599, "zone quest"),
    "Glenumbra - The Wyrd Tree's Roots Zone Quest":     ESOLocationData("Glenumbra",     eso_quest_id + 3016, "zone quest"),
    "Glenumbra - Seeking the Guardians Zone Quest":     ESOLocationData("Glenumbra",     eso_quest_id + 3060, "zone quest"),
    "Glenumbra - Champion of the Guardians Zone Quest": ESOLocationData("Glenumbra",     eso_quest_id + 3063, "zone quest"),
    "Glenumbra - Reclaiming the Elements Zone Quest":   ESOLocationData("Glenumbra",     eso_quest_id + 3191, "zone quest"),
    "Glenumbra - Purifying the Wyrd Tree Zone Quest":   ESOLocationData("Glenumbra",     eso_quest_id + 3235, "zone quest"),
    "Glenumbra - A Duke in Exile Zone Quest":           ESOLocationData("Glenumbra",     eso_quest_id + 974, "zone quest"),
    "Glenumbra - Wolves in the Fold Zone Quest":        ESOLocationData("Glenumbra",     eso_quest_id + 3013, "zone quest"),
    "Glenumbra - Lineage of Tooth and Claw Zone Quest": ESOLocationData("Glenumbra",     eso_quest_id + 3018, "zone quest"),
    "Glenumbra - Ripple Effect Zone Quest":             ESOLocationData("Glenumbra",     eso_quest_id + 3027, "zone quest"),
    "Glenumbra - A Step Back in Time Zone Quest":       ESOLocationData("Glenumbra",     eso_quest_id + 3047, "zone quest"),
    "Glenumbra - The Nameless Soldier Zone Quest":      ESOLocationData("Glenumbra",     eso_quest_id + 3049, "zone quest"),
    "Glenumbra - Rally Cry Zone Quest":                 ESOLocationData("Glenumbra",     eso_quest_id + 3064, "zone quest"),
    "Glenumbra - A Lingering Hope Zone Quest":          ESOLocationData("Glenumbra",     eso_quest_id + 3174, "zone quest"),
    "Glenumbra - Hidden in Flames Zone Quest":          ESOLocationData("Glenumbra",     eso_quest_id + 3189, "zone quest"),
    "Glenumbra - The Fall of Faolchu Zone Quest":       ESOLocationData("Glenumbra",     eso_quest_id + 3267, "zone quest"),
    "Glenumbra - The Lion Guard's Stand Zone Quest":    ESOLocationData("Glenumbra",     eso_quest_id + 3082, "zone quest"),
    "Glenumbra - Mastering the Talisman Zone Quest":    ESOLocationData("Glenumbra",     eso_quest_id + 3277, "zone quest"),
    "Glenumbra - Mists of Corruption Zone Quest":       ESOLocationData("Glenumbra",     eso_quest_id + 3338, "zone quest"),
    "Glenumbra - The Labyrinth Zone Quest":             ESOLocationData("Glenumbra",     eso_quest_id + 3357, "zone quest"),
    "Glenumbra - Angof the Gravesinger Zone Quest":     ESOLocationData("Glenumbra",     eso_quest_id + 3379, "zone quest"),

    "Rivenspire - Shornhelm Divided Zone Quest":        ESOLocationData("Rivenspire",    eso_quest_id + 4902, "zone quest"),
    "Rivenspire - Dream-Walk into Darkness Zone Quest": ESOLocationData("Rivenspire",    eso_quest_id +4903, "zone quest"),
    "Rivenspire - The Blood-Splattered Shield Zone Quest":ESOLocationData("Rivenspire",  eso_quest_id +465, "zone quest"),
    "Rivenspire - The Concealing Veil Zone Quest":      ESOLocationData("Rivenspire",    eso_quest_id +4857, "zone quest"),
    "Rivenspire - Northpoint in Peril Zone Quest":      ESOLocationData("Rivenspire",    eso_quest_id +4958, "zone quest"),
    "Rivenspire - The Liberation of Northpoint Zone Quest":ESOLocationData("Rivenspire", eso_quest_id +4972, "zone quest"),
    "Rivenspire - Puzzle of the Pass Zone Quest":       ESOLocationData("Rivenspire",    eso_quest_id +5024, "zone quest"),
    "Rivenspire - The Lightless Remnant Zone Quest":    ESOLocationData("Rivenspire",    eso_quest_id +4884, "zone quest"),
    "Rivenspire - The Crown of Shormhelm Zone Quest":   ESOLocationData("Rivenspire",    eso_quest_id +4936, "zone quest"),

    "Stormhaven - A Dangerous Dream Zone Quest":        ESOLocationData("Stormhaven", eso_quest_id +3423, "zone quest"),
    "Stormhaven - False Accusations Zone Quest":        ESOLocationData("Stormhaven", eso_quest_id +2556, "zone quest"),
    "Stormhaven - Army at the Gates Zone Quest":        ESOLocationData("Stormhaven", eso_quest_id +2552, "zone quest"),
    "Stormhaven - Two Sides to Every Coin Zone Quest":  ESOLocationData("Stormhaven", eso_quest_id +2564, "zone quest"),
    "Stormhaven - Life of the Duchess Zone Quest":      ESOLocationData("Stormhaven", eso_quest_id +2566, "zone quest"),
    "Stormhaven - The Safety of the Kingdom Zone Quest":ESOLocationData("Stormhaven", eso_quest_id +2567, "zone quest"),
    "Stormhaven - Tracking Sir Hughes Zone Quest":      ESOLocationData("Stormhaven", eso_quest_id +2576, "zone quest"),
    "Stormhaven - The Flame of Dissent Zone Quest":     ESOLocationData("Stormhaven", eso_quest_id +736, "zone quest"),
    "Stormhaven - Retaking Firebrand Keep Zone Quest":  ESOLocationData("Stormhaven", eso_quest_id +737, "zone quest"),
    "Stormhaven - Sir Hughes' Fate Zone Quest":         ESOLocationData("Stormhaven", eso_quest_id +467, "zone quest"),
    "Stormhaven - Fire in the Fields Zone Quest":       ESOLocationData("Stormhaven", eso_quest_id +1563, "zone quest"),
    "Stormhaven - Azura's Guardian Zone Quest":         ESOLocationData("Stormhaven", eso_quest_id +1529, "zone quest"),
    "Stormhaven - A Prison of Sleep Zone Quest":        ESOLocationData("Stormhaven", eso_quest_id +1541, "zone quest"),
    "Stormhaven - Pursuing the Shard Zone Quest":       ESOLocationData("Stormhaven", eso_quest_id +499, "zone quest"),
    "Stormhaven - The Signet Ring Zone Quest":          ESOLocationData("Stormhaven", eso_quest_id +2495, "zone quest"),
    "Stormhaven - Evidence Against Adima Zone Quest":   ESOLocationData("Stormhaven", eso_quest_id +2496, "zone quest"),
    "Stormhaven - Saving Hosni Zone Quest":             ESOLocationData("Stormhaven", eso_quest_id +2497, "zone quest"),
    "Stormhaven - The Return of the Dream Shard Zone Quest":ESOLocationData("Stormhaven", eso_quest_id +1633, "zone quest"),
    "Stormhaven - Another Omen Zone Quest":             ESOLocationData("Stormhaven", eso_quest_id +1639, "zone quest"),
    "Stormhaven - General Godrun's Orders Zone Quest":  ESOLocationData("Stormhaven", eso_quest_id +1437, "zone quest"),
    "Stormhaven - Ending the Ogre Threat Zone Quest":   ESOLocationData("Stormhaven", eso_quest_id +1346, "zone quest"),
    "Stormhaven - Godrun's Dream Zone Quest":           ESOLocationData("Stormhaven", eso_quest_id +3637, "zone quest"),
    "Stormhaven - Azura's Aid Zone Quest":              ESOLocationData("Stormhaven", eso_quest_id +521, "zone quest"),
    "Stormhaven - Vaermina's Gambit Zone Quest":        ESOLocationData("Stormhaven", eso_quest_id +575, "zone quest"),

    "Bangkorai - A City in Black Zone Quest":           ESOLocationData("Bangkorai", eso_quest_id +1799, "zone quest"),
    "Bangkorai - Imperial Infiltration Zone Quest":     ESOLocationData("Bangkorai", eso_quest_id +3280, "zone quest"),
    "Bangkorai - Beyond the Call Zone Quest":           ESOLocationData("Bangkorai", eso_quest_id +4899, "zone quest"),
    "Bangkorai - Heart of Evil Zone Quest":             ESOLocationData("Bangkorai", eso_quest_id +1834, "zone quest"),
    "Bangkorai - The Parlay Zone Quest":                ESOLocationData("Bangkorai", eso_quest_id +4891, "zone quest"),
    "Bangkorai - Storming the Garrison Zone Quest":     ESOLocationData("Bangkorai", eso_quest_id +4912, "zone quest"),
    "Bangkorai - Hallin's Burden Zone Quest":           ESOLocationData("Bangkorai", eso_quest_id +2016, "zone quest"),
    "Bangkorai - The Lion's Den Zone Quest":            ESOLocationData("Bangkorai", eso_quest_id +2017, "zone quest"),
    "Bangkorai - A Thirst for Revolution Zone Quest":   ESOLocationData("Bangkorai", eso_quest_id +2018, "zone quest"),
    "Bangkorai - The Shifting Sands of Fate Zone Quest":ESOLocationData("Bangkorai", eso_quest_id +4918, "zone quest"),
    "Bangkorai - Trials and Tribulations Zone Quest":   ESOLocationData("Bangkorai", eso_quest_id +4959, "zone quest"),
    "Bangkorai - To Walk on far Shores Zone Quest":     ESOLocationData("Bangkorai", eso_quest_id +4960, "zone quest"),

    "Alik'r Desert - Risen From the Depths Zone Quest": ESOLocationData("Alik'r Desert", eso_quest_id +3333, "zone quest"),
    "Alik'r Desert - Rise of the Dead Zone Quest":      ESOLocationData("Alik'r Desert", eso_quest_id +2130, "zone quest"),
    "Alik'r Desert - The Impervious Vault Zone Quest":  ESOLocationData("Alik'r Desert", eso_quest_id +2146, "zone quest"),
    "Alik'r Desert - Morwha's Curse Zone Quest":        ESOLocationData("Alik'r Desert", eso_quest_id +4672, "zone quest"),
    "Alik'r Desert - The Initiation Zone Quest":        ESOLocationData("Alik'r Desert", eso_quest_id +4686, "zone quest"),
    "Alik'r Desert - Ash'abah Rising Zone Quest":       ESOLocationData("Alik'r Desert", eso_quest_id +3190, "zone quest"),
    "Alik'r Desert - Tu'whacca's Breath Zone Quest":    ESOLocationData("Alik'r Desert", eso_quest_id +2184, "zone quest"),
    "Alik'r Desert - A Reckoning with Uwafa Zone Quest":ESOLocationData("Alik'r Desert", eso_quest_id +2192, "zone quest"),
    "Alik'r Desert - Gone Missing Zone Quest":          ESOLocationData("Alik'r Desert", eso_quest_id +2251, "zone quest"),
    "Alik'r Desert - Alasan's Plot Zone Quest":         ESOLocationData("Alik'r Desert", eso_quest_id +2222, "zone quest"),
    "Alik'r Desert - March of the Ra Gada Zone Quest":  ESOLocationData("Alik'r Desert", eso_quest_id +2356, "zone quest"),
    "Alik'r Desert - Trials of the Hero Zone Quest":    ESOLocationData("Alik'r Desert", eso_quest_id +3296, "zone quest"),
    "Alik'r Desert - Imperial Incursion Zone Quest":    ESOLocationData("Alik'r Desert", eso_quest_id +2404, "zone quest"),
    "Alik'r Desert - Amputating the Hand Zone Quest":   ESOLocationData("Alik'r Desert", eso_quest_id +2997, "zone quest"),
    "Alik'r Desert - Restoring the Ansei Wards Zone Quest":ESOLocationData("Alik'r Desert", eso_quest_id +2998, "zone quest"),

    "Craglorn - The Star Gazers Zone Quest":            ESOLocationData("Craglorn", eso_quest_id +5747, "zone quest"),
    "Craglorn - The Corrupted Stone Zone Quest":        ESOLocationData("Craglorn", eso_quest_id +5746, "zone quest"),
    "Craglorn - The Warrior's Call Zone Quest":         ESOLocationData("Craglorn", eso_quest_id +5748, "zone quest"),
    "Craglorn - Elemental Army Zone Quest":             ESOLocationData("Craglorn", eso_quest_id +5761, "zone quest"),
    "Craglorn - The Shattered and the Lost Zone Quest": ESOLocationData("Craglorn", eso_quest_id +5763, "zone quest"),
    "Craglorn - The Missing Guardian Zone Quest":       ESOLocationData("Craglorn", eso_quest_id +5760, "zone quest"),
    "Craglorn - Slithering Brood Zone Quest":           ESOLocationData("Craglorn", eso_quest_id +5768, "zone quest"),
    "Craglorn - The Serpent's Fang Zone Quest":         ESOLocationData("Craglorn", eso_quest_id +5769, "zone quest"),
    "Craglorn - Dawn of the Exalted Viper Zone Quest":  ESOLocationData("Craglorn", eso_quest_id +5771, "zone quest"),
    "Craglorn - The Time-Lost Warrior Zone Quest":      ESOLocationData("Craglorn", eso_quest_id +5776, "zone quest"),

    "Bleakrock Isle - Hozzin's Folly Zone Quest":       ESOLocationData("Bleakrock Isle", eso_quest_id +3987, "zone quest"),
    "Bleakrock Isle - The Frozen Man Zone Quest":       ESOLocationData("Bleakrock Isle", eso_quest_id +3995, "zone quest"),
    "Bleakrock Isle - What Waits Beneath Zone Quest":   ESOLocationData("Bleakrock Isle", eso_quest_id +3992, "zone quest"),
    "Bleakrock Isle - The Missing of Bleakrock Zone Quest":ESOLocationData("Bleakrock Isle", eso_quest_id +4016, "zone quest"),
    "Bleakrock Isle - Sparking the Flame Zone Quest":   ESOLocationData("Bleakrock Isle", eso_quest_id +4002, "zone quest"),
    "Bleakrock Isle - Escape from Bleakrock Zone Quest":ESOLocationData("Bleakrock Isle", eso_quest_id +3991, "zone quest"),

    "Bal Foyen - If By Sea Zone Quest":                 ESOLocationData("Bal Foyen", eso_quest_id +4023, "zone quest"),
    "Bal Foyen - Crossroads Zone Quest":                ESOLocationData("Bal Foyen", eso_quest_id +4041, "zone quest"),
    "Bal Foyen - Breaking The Tide / Zeren in Peril Zone Quest":ESOLocationData("Bal Foyen", eso_quest_id +4028, "zone quest"),

    "Stonefalls - Legacy of the Ancestors Zone Quest":  ESOLocationData("Stonefalls", eso_quest_id +3585, "zone quest"),
    "Stonefalls - Delaying the Daggers Zone Quest":     ESOLocationData("Stonefalls", eso_quest_id +3587, "zone quest"),
    "Stonefalls - City Under Siege Zone Quest":         ESOLocationData("Stonefalls", eso_quest_id +3588, "zone quest"),
    "Stonefalls - Wake the Dead Zone Quest":            ESOLocationData("Stonefalls", eso_quest_id +3615, "zone quest"),
    "Stonefalls - Rending Flames Zone Quest":           ESOLocationData("Stonefalls", eso_quest_id +3616, "zone quest"),
    "Stonefalls - Restoring the Guardians Zone Quest":  ESOLocationData("Stonefalls", eso_quest_id +3734, "zone quest"),
    "Stonefalls - The Death of Balreth Zone Quest":     ESOLocationData("Stonefalls", eso_quest_id +3735, "zone quest"),
    "Stonefalls - The Coral Heart Zone Quest":          ESOLocationData("Stonefalls", eso_quest_id +3584, "zone quest"),
    "Stonefalls - Breaking for Virak Zone Quest":       ESOLocationData("Stonefalls", eso_quest_id +3632, "zone quest"),
    "Stonefalls - Evening the Odds Zone Quest":         ESOLocationData("Stonefalls", eso_quest_id +3633, "zone quest"),
    "Stonefalls - The General's Demise Zone Quest":     ESOLocationData("Stonefalls", eso_quest_id +3634, "zone quest"),
    "Stonefalls - Aggressive Negotiations Zone Quest":  ESOLocationData("Stonefalls", eso_quest_id +3685, "zone quest"),
    "Stonefalls - Saving the Son Zone Quest":           ESOLocationData("Stonefalls", eso_quest_id +3696, "zone quest"),
    "Stonefalls - Climbing the Spire Zone Quest":       ESOLocationData("Stonefalls", eso_quest_id +3826, "zone quest"),
    "Stonefalls - Opening the Portal Zone Quest":       ESOLocationData("Stonefalls", eso_quest_id +3837, "zone quest"),
    "Stonefalls - Salal's Final Defeat Zone Quest":     ESOLocationData("Stonefalls", eso_quest_id +3868, "zone quest"),

    "Deshaan - Bad Medicine Zone Quest":                ESOLocationData("Deshaan", eso_quest_id +5057, "zone quest"),
    "Deshaan - Proprietary Formula Zone Quest":         ESOLocationData("Deshaan", eso_quest_id +5067, "zone quest"),
    "Deshaan - Quest For the Cure Zone Quest":          ESOLocationData("Deshaan", eso_quest_id +5068, "zone quest"),
    "Deshaan - For Their Own Protection Zone Quest":    ESOLocationData("Deshaan", eso_quest_id +3610, "zone quest"),
    "Deshaan - Unwanted Guests Zone Quest":             ESOLocationData("Deshaan", eso_quest_id +3659, "zone quest"),
    "Deshaan - Fighting Back Zone Quest":               ESOLocationData("Deshaan", eso_quest_id +3652, "zone quest"),
    "Deshaan - Ratting Them Out / A Timely Matter Zone Quest":ESOLocationData("Deshaan", eso_quest_id +3653, "zone quest"),
    "Deshaan - Hiding in Plain Sight Zone Quest":       ESOLocationData("Deshaan", eso_quest_id +3660, "zone quest"),
    "Deshaan - Death Trap Zone Quest":                  ESOLocationData("Deshaan", eso_quest_id +3673, "zone quest"),
    "Deshaan - Payback Zone Quest":                     ESOLocationData("Deshaan", eso_quest_id +3705, "zone quest"),
    "Deshaan - Plague Bringer Zone Quest":              ESOLocationData("Deshaan", eso_quest_id +3797, "zone quest"),
    "Deshaan - A Favor Returned Zone Quest":            ESOLocationData("Deshaan", eso_quest_id +4453, "zone quest"),
    "Deshaan - The Mournhold Underground Zone Quest":   ESOLocationData("Deshaan", eso_quest_id +4459, "zone quest"),
    "Deshaan - The Seal of Three Zone Quest":           ESOLocationData("Deshaan", eso_quest_id +3817, "zone quest"),
    "Deshaan - Restless Spirits Zone Quest":            ESOLocationData("Deshaan", eso_quest_id +3820, "zone quest"),
    "Deshaan - Rescue and Revenge Zone Quest":          ESOLocationData("Deshaan", eso_quest_id +3852, "zone quest"),
    "Deshaan - A Saint Asunder Zone Quest":             ESOLocationData("Deshaan", eso_quest_id +3818, "zone quest"),
    "Deshaan - Into the Mouth of Madness Zone Quest":   ESOLocationData("Deshaan", eso_quest_id +3749, "zone quest"),
    "Deshaan - Motive for Heresy Zone Quest":           ESOLocationData("Deshaan", eso_quest_id +3810, "zone quest"),
    "Deshaan - The Judgement of Veloth Zone Quest":     ESOLocationData("Deshaan", eso_quest_id +3831, "zone quest"),

    "Shadowfen - Three Tender Souls Zone Quest":        ESOLocationData("Shadowfen", eso_quest_id +3686, "zone quest"),
    "Shadowfen - Getting to the Truth Zone Quest":      ESOLocationData("Shadowfen", eso_quest_id +3687, "zone quest"),
    "Shadowfen - Trail of the Skin-Stealer Zone Quest": ESOLocationData("Shadowfen", eso_quest_id +4587, "zone quest"),
    "Shadowfen - The Skin-Stealer's Lair Zone Quest":   ESOLocationData("Shadowfen", eso_quest_id +4590, "zone quest"),
    "Shadowfen - Keepers of the Shell Zone Quest":      ESOLocationData("Shadowfen", eso_quest_id +4606, "zone quest"),
    "Shadowfen - The Domminion's Alchemist Zone Quest": ESOLocationData("Shadowfen", eso_quest_id +3909, "zone quest"),
    "Shadowfen - The Dream of the Hist Zone Quest":     ESOLocationData("Shadowfen", eso_quest_id +3910, "zone quest"),

    "Eastmarch - Shadows Over Windhelm Zone Quest":     ESOLocationData("Eastmarch", eso_quest_id +4058, "zone quest"),
    "Eastmarch - The Konunleikar Zone Quest":           ESOLocationData("Eastmarch", eso_quest_id +4059, "zone quest"),
    "Eastmarch - Windhelm's Champion Zone Quest":       ESOLocationData("Eastmarch", eso_quest_id +4060, "zone quest"),
    "Eastmarch - One Victor, One King Zone Quest":      ESOLocationData("Eastmarch", eso_quest_id +4061, "zone quest"),
    "Eastmarch - Blindsided Zone Quest":                ESOLocationData("Eastmarch", eso_quest_id +4062, "zone quest"),
    "Eastmarch - Sleep for the Dead Zone Quest":        ESOLocationData("Eastmarch", eso_quest_id +4071, "zone quest"),
    "Eastmarch - Sleeping on the Job Zone Quest":       ESOLocationData("Eastmarch", eso_quest_id +4150, "zone quest"),
    "Eastmarch - The Pride of a Prince Zone Quest":     ESOLocationData("Eastmarch", eso_quest_id +4158, "zone quest"),
    "Eastmarch - The War Council Zone Quest":           ESOLocationData("Eastmarch", eso_quest_id +4166, "zone quest"),
    "Eastmarch - Lifeline Zone Quest":                  ESOLocationData("Eastmarch", eso_quest_id +4203, "zone quest"),
    "Eastmarch - Our Poor Town Zone Quest":             ESOLocationData("Eastmarch", eso_quest_id +4205, "zone quest"),
    "Eastmarch - A Right to Live Zone Quest":           ESOLocationData("Eastmarch", eso_quest_id +4075, "zone quest"),
    "Eastmarch - The Better of Two Evils Zone Quest":   ESOLocationData("Eastmarch", eso_quest_id +4106, "zone quest"),
    "Eastmarch - Eternal Slumber Zone Quest":           ESOLocationData("Eastmarch", eso_quest_id +4115, "zone quest"),
    "Eastmarch - Gods Save the King Zone Quest":        ESOLocationData("Eastmarch", eso_quest_id +4123, "zone quest"),
    "Eastmarch - Making Amends Zone Quest":             ESOLocationData("Eastmarch", eso_quest_id +4069, "zone quest"),
    "Eastmarch - A Council of Thanes Zone Quest":       ESOLocationData("Eastmarch", eso_quest_id +4078, "zone quest"),
    "Eastmarch - Snow and Flame Zone Quest":            ESOLocationData("Eastmarch", eso_quest_id +4116, "zone quest"),
    "Eastmarch - Songs of Sovngarde Zone Quest":        ESOLocationData("Eastmarch", eso_quest_id +4117, "zone quest"),

    "The Rift - Beneath the Stone Zone Quest":          ESOLocationData("The Rift", eso_quest_id +3919, "zone quest"),
    "The Rift - Unearthed Zone Quest":                  ESOLocationData("The Rift", eso_quest_id +3920, "zone quest"),
    "The Rift - Storming the Hall Zone Quest":          ESOLocationData("The Rift", eso_quest_id +3974, "zone quest"),
    "The Rift - Dangerous Union Zone Quest":            ESOLocationData("The Rift", eso_quest_id +3928, "zone quest"),
    "The Rift - Gift of the Worm Zone Quest":           ESOLocationData("The Rift", eso_quest_id +3957, "zone quest"),
    "The Rift - Through the Shroud Zone Quest":         ESOLocationData("The Rift", eso_quest_id +3968, "zone quest"),
    "The Rift - Concealed Weapons Zone Quest":          ESOLocationData("The Rift", eso_quest_id +4153, "zone quest"),
    "The Rift - Tomb Beneath the Mountain Zone Quest":  ESOLocationData("The Rift", eso_quest_id +3978, "zone quest"),
    "The Rift - The Shackled Guardian Zone Quest":      ESOLocationData("The Rift", eso_quest_id +4147, "zone quest"),
    "The Rift - Shattered Hopes Zone Quest":            ESOLocationData("The Rift", eso_quest_id +4139, "zone quest"),
    "The Rift - A Giant in Smokefrost Peaks Zone Quest":ESOLocationData("The Rift", eso_quest_id +4164, "zone quest"),
    "The Rift - In His Wake Zone Quest":                ESOLocationData("The Rift", eso_quest_id +3927, "zone quest"),
    "The Rift - Pulled Under Zone Quest":               ESOLocationData("The Rift", eso_quest_id +4135, "zone quest"),
    "The Rift - Securing the Pass Zone Quest":          ESOLocationData("The Rift", eso_quest_id +4186, "zone quest"),
    "The Rift - Stomping Sinmur Zone Quest":            ESOLocationData("The Rift", eso_quest_id +4188, "zone quest"),

    "Khenarthi's Roost - Storm on the Horizon Zone Quest":ESOLocationData("Khenarthi's Roost", eso_quest_id +4680, "zone quest"),
    "Khenarthi's Roost - Cast Adrift Zone Quest":       ESOLocationData("Khenarthi's Roost", eso_quest_id +4620, "zone quest"),
    "Khenarthi's Roost - Tears of the Two Moons Zone Quest":ESOLocationData("Khenarthi's Roost", eso_quest_id +4625, "zone quest"),
    "Khenarthi's Roost - The Perils of Diplomacy Zone Quest":ESOLocationData("Khenarthi's Roost", eso_quest_id +4624, "zone quest"),
    "Khenarthi's Roost - The Tempest Unleashed Zone Quest":ESOLocationData("Khenarthi's Roost", eso_quest_id +4621, "zone quest"),

    "Auridon - Ensuing Security Zone Quest":            ESOLocationData("Auridon", eso_quest_id +4255, "zone quest"),
    "Auridon - A Hostile Situation Zone Quest":         ESOLocationData("Auridon", eso_quest_id +4256, "zone quest"),
    "Auridon - In the Name of the Queen Zone Quest":    ESOLocationData("Auridon", eso_quest_id +4217, "zone quest"),
    "Auridon - Rites of the Queen Zone Quest":          ESOLocationData("Auridon", eso_quest_id +4222, "zone quest"),
    "Auridon - Putting the Pieces Together Zone Quest": ESOLocationData("Auridon", eso_quest_id +4293, "zone quest"),
    "Auridon - The Unveiling Zone Quest":               ESOLocationData("Auridon", eso_quest_id +4294, "zone quest"),
    "Auridon - Lifting the Veil Zone Quest":            ESOLocationData("Auridon", eso_quest_id +4330, "zone quest"),
    "Auridon - Wearing the Veil Zone Quest":            ESOLocationData("Auridon", eso_quest_id +4331, "zone quest"),
    "Auridon - The Veil Falls Zone Quest":              ESOLocationData("Auridon", eso_quest_id +4345, "zone quest"),
    "Auridon - Through the Ashes Zone Quest":           ESOLocationData("Auridon", eso_quest_id +4355, "zone quest"),
    "Auridon - Breaking the Barrier Zone Quest":        ESOLocationData("Auridon", eso_quest_id +4260, "zone quest"),
    "Auridon - Sever All Ties Zone Quest":              ESOLocationData("Auridon", eso_quest_id +4261, "zone quest"),

    "Grahtwood - Unsafe Haven Zone Quest":              ESOLocationData("Grahtwood", eso_quest_id +4396, "zone quest"),
    "Grahtwood - The Great Tree Zone Quest":            ESOLocationData("Grahtwood", eso_quest_id +4896, "zone quest"),
    "Grahtwood - The Honor of the Queen Zone Quest":    ESOLocationData("Grahtwood", eso_quest_id +4943, "zone quest"),
    "Grahtwood - Fit to Rule Zone Quest":               ESOLocationData("Grahtwood", eso_quest_id +4951, "zone quest"),
    "Grahtwood - The Grip of Madness Zone Quest":       ESOLocationData("Grahtwood", eso_quest_id +4868, "zone quest"),
    "Grahtwood - Lost in Study Zone Quest":             ESOLocationData("Grahtwood", eso_quest_id +4385, "zone quest"),
    "Grahtwood - Heart of the Matter Zone Quest":       ESOLocationData("Grahtwood", eso_quest_id +4386, "zone quest"),
    "Grahtwood - A Lasting Winter Zone Quest":          ESOLocationData("Grahtwood", eso_quest_id +4885, "zone quest"),
    "Grahtwood - The Orrery of Elden Root Zone Quest":  ESOLocationData("Grahtwood", eso_quest_id +4922, "zone quest"),

    "Greenshade - The Staff of Magnus Zone Quest":      ESOLocationData("Greenshade", eso_quest_id +4735, "zone quest"),
    "Greenshade - Frighten the Fearsome Zone Quest":    ESOLocationData("Greenshade", eso_quest_id +4573, "zone quest"),
    "Greenshade - Audience with the Wilderking Zone Quest":ESOLocationData("Greenshade", eso_quest_id +4593, "zone quest"),
    "Greenshade - The Witch of Siltatar Zone Quest":    ESOLocationData("Greenshade", eso_quest_id +4586, "zone quest"),
    "Greenshade - Throne of the Wilderking Zone Quest": ESOLocationData("Greenshade", eso_quest_id +4750, "zone quest"),
    "Greenshade - Veil of Illusion Zone Quest":         ESOLocationData("Greenshade", eso_quest_id +4574, "zone quest"),
    "Greenshade - Double Jepardy Zone Quest":           ESOLocationData("Greenshade", eso_quest_id +4580, "zone quest"),
    "Greenshade - A Storm Upon the Shore Zone Quest":   ESOLocationData("Greenshade", eso_quest_id +4739, "zone quest"),
    "Greenshade - Pelidil's End Zone Quest":            ESOLocationData("Greenshade", eso_quest_id +4765, "zone quest"),
    "Greenshade - Retaking the Pass Zone Quest":        ESOLocationData("Greenshade", eso_quest_id +4546, "zone quest"),
    "Greenshade - Right of Theft Zone Quest":           ESOLocationData("Greenshade", eso_quest_id +4601, "zone quest"),
    "Greenshade - The Blight of the Bosmer Zone Quest": ESOLocationData("Greenshade", eso_quest_id +4608, "zone quest"),
    "Greenshade - Striking at the Heart Zone Quest":    ESOLocationData("Greenshade", eso_quest_id +4690, "zone quest"),

    "Malabal Tor - House and Home Zone Quest":          ESOLocationData("Malabal Tor", eso_quest_id +4193, "zone quest"),
    "Malabal Tor - One Fell Swoop Zone Quest":          ESOLocationData("Malabal Tor", eso_quest_id +4194, "zone quest"),
    "Malabal Tor - The Drublog of Dra'bul Zone Quest":  ESOLocationData("Malabal Tor", eso_quest_id +4458, "zone quest"),
    "Malabal Tor - Reap what is Sown Zone Quest":       ESOLocationData("Malabal Tor", eso_quest_id +4452, "zone quest"),
    "Malabal Tor - The Prisoner of Hathsogur Zone Quest":ESOLocationData("Malabal Tor", eso_quest_id +4124, "zone quest"),
    "Malabal Tor - Restore the Silvenar Zone Quest":    ESOLocationData("Malabal Tor", eso_quest_id +4143, "zone quest"),

    "Reaper's March - Grim Situation Zone Quest":       ESOLocationData("Reaper's March", eso_quest_id +4460, "zone quest"),
    "Reaper's March - Grimmer Still Zone Quest":        ESOLocationData("Reaper's March", eso_quest_id +4461, "zone quest"),
    "Reaper's March - The Colovian Occupation Zone Quest":ESOLocationData("Reaper's March", eso_quest_id +4652, "zone quest"),
    "Reaper's March - Stonefire Machinations Zone Quest":ESOLocationData("Reaper's March", eso_quest_id +4653, "zone quest"),
    "Reaper's March - A Door into Moonlight Zone Quest":ESOLocationData("Reaper's March", eso_quest_id +4689, "zone quest"),
    "Reaper's March - The First Step Zone Quest":       ESOLocationData("Reaper's March", eso_quest_id +4712, "zone quest"),
    "Reaper's March - Motes in the Moonlight Zone Quest":ESOLocationData("Reaper's March", eso_quest_id +4479, "zone quest"),
    "Reaper's March - The Fires of Dune Zone Quest":    ESOLocationData("Reaper's March", eso_quest_id +4550, "zone quest"),
    "Reaper's March - The Moonlit Path Zone Quest":     ESOLocationData("Reaper's March", eso_quest_id +4719, "zone quest"),
    "Reaper's March - The Den of Lorkhaj Zone Quest":   ESOLocationData("Reaper's March", eso_quest_id +4720, "zone quest"),

    "Coldharbor - The Hollow City Zone Quest":          ESOLocationData("Coldharbor", eso_quest_id +5605, "zone quest"),
    "Coldharbor - The Army of Meridia Zone Quest":      ESOLocationData("Coldharbor", eso_quest_id +4610, "zone quest"),
    "Coldharbor - Into the Woods Zone Quest":           ESOLocationData("Coldharbor", eso_quest_id +4399, "zone quest"),
    "Coldharbor - Vanus Unleashed Zone Quest":          ESOLocationData("Coldharbor", eso_quest_id +4626, "zone quest"),
    "Coldharbor - An Unusual Circumstance / The Shadows Embrace Zone Quest":ESOLocationData("Coldharbor", eso_quest_id +4654, "zone quest"),
    "Coldharbor - Light from the Darkness Zone quest":  ESOLocationData("Coldharbor", eso_quest_id +4602, "zone quest"),
    "Coldharbor - Breaking the Shakle Zone Quest":      ESOLocationData("Coldharbor", eso_quest_id +4730, "zone quest"),
    "Coldharbor - Crossing the Chasm Zone Quest":       ESOLocationData("Coldharbor", eso_quest_id +4701, "zone quest"),
    "Coldharbor - The Harvest Heart Zone Quest":        ESOLocationData("Coldharbor", eso_quest_id +4715, "zone quest"),
    "Coldharbor - The Citadel Must Fall Zone Quest":    ESOLocationData("Coldharbor", eso_quest_id +4774, "zone quest"),
    "Coldharbor - The Final Assault Zone Quest":        ESOLocationData("Coldharbor", eso_quest_id +4758, "zone quest"),

    "Main Quest - The Harborage":                       ESOLocationData("Main Quest", eso_quest_id +4831, "main quest"),
    "Main Quest - Daughter of Giants":                  ESOLocationData("Main Quest", eso_quest_id +4474, "main quest"),
    "Main Quest - Chasing Shadows":                     ESOLocationData("Main Quest", eso_quest_id +4552, "main quest"),
    "Main Quest - Castle of the Worm":                  ESOLocationData("Main Quest", eso_quest_id +4607, "main quest"),
    "Main Quest - The Tharn Speaks":                    ESOLocationData("Main Quest", eso_quest_id +4764, "main quest"),
    "Main Quest - Halls of Torment":                    ESOLocationData("Main Quest", eso_quest_id +4836, "main quest"),
    "Main Quest - Valley of Blades":                    ESOLocationData("Main Quest", eso_quest_id +4837, "main quest"),
    "Main Quest - Shadow of Sancre Tor":                ESOLocationData("Main Quest", eso_quest_id +4867, "main quest"),
    "Main Quest - Council of the Five Companions":      ESOLocationData("Main Quest", eso_quest_id +4832, "main quest"),
    "Main Quest - Message Across Tamriel":              ESOLocationData("Main Quest", eso_quest_id +4780, "main quest"),
    "Main Quest - The Weight of Three Crowns":          ESOLocationData("Main Quest", eso_quest_id +4783, "main quest"),
    "Main Quest - God of Schemes":                      ESOLocationData("Main Quest", eso_quest_id +4847, "main quest"),
}